export const LOGIN = 'LOGIN';
export const SWITCH_APARTAMENT = 'SWITCH_APARTAMENT';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_CURRENT_APARTAMENT = 'SET_CURRENT_APARTAMENT';
